### Create project
POST http://localhost:8184/api/v1/control/projects
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "flagforge-demo",
  "name": "FlagForge Demo Project"
}

### Create environment
@eProjectId =c259ffc6-c58e-4452-922b-1e66d6f9a701

POST http://localhost:8184/api/v1/control/projects/{{eProjectId}}/envs
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "dev",
  "name": "Development"
}

### Create flag
@fProjectId =c259ffc6-c58e-4452-922b-1e66d6f9a701
@environmentKey = dev
POST http://localhost:8184/api/v1/control/projects/{{fProjectId}}/envs/{{environmentKey}}/flags
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "new_backend_flow",
  "type": "BOOLEAN",
  "enabled": true,
  "defaultVariant": null,
  "rules": [],
  "salt": null
}

