### Create project
POST http://localhost:8184/api/v1/control/projects
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "flagforge-demo",
  "name": "FlagForge Demo Project"
}

### Create environment
@eProjectId =b626f106-184f-4cc3-a8cf-7c96ce707cd1

POST http://localhost:8184/api/v1/control/projects/{{eProjectId}}/envs
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "dev",
  "name": "Development"
}

### Create flag
@fProjectId =b626f106-184f-4cc3-a8cf-7c96ce707cd1
@environmentKey = dev
POST http://localhost:8184/api/v1/control/projects/{{fProjectId}}/envs/{{environmentKey}}/flags
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "new_backend",
  "type": "BOOLEAN",
  "enabled": true,
  "defaultVariant": null,
  "rules": [],
  "salt": null
}

