### Create project
POST http://localhost:8184/api/v1/control/projects
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "flagforge-demo23",
  "name": "FlagForge Demo Project"
}

### Create environment
@eProjectId =9a321dc3-a8b5-4340-a127-a1121de745f4

POST http://localhost:8184/api/v1/control/projects/{{eProjectId}}/envs
X-Actor-Id: test-user
Content-Type: application/json

{
  "key": "dev",
  "name": "Development"
}

### Create flag
@fProjectId =9a321dc3-a8b5-4340-a127-a1121de745f4
@environmentKey = dev
POST http://localhost:8184/api/v1/control/projects/{{fProjectId}}/envs/{{environmentKey}}/flags
X-Actor-Id: "test-user"
Content-Type: application/json

{
  "key": "new_backend",
  "type": "BOOLEAN",
  "enabled": true,
  "defaultVariant": null,
  "rules": [],
  "salt": null
}

###
@flagId =5bcbb7e2-a0bd-4865-b8ce-bdcc5595f47b
POST http://localhost:8184/api/v1/control/flags/{{flagId}}:toggle
Content-Type: application/json
X-Actor-Id: alice

{
  "expectedVersion": 2,
  "enabled": false
}
